steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gestao-acesso:$TAG_NAME', '-t', 'gcr.io/$PROJECT_ID/api-gestao-acesso:latest', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/api-gestao-acesso:$TAG_NAME']

options:
  logging: CLOUD_LOGGING_ONLY

images: ['gcr.io/$PROJECT_ID/api-gestao-acesso']

substitutions:
  _REPO_NAME: api-gestao-acesso

tags: ['api-gestao-acesso', '$_REPO_NAME']
