apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gestaoacesso
  labels:
    app: api-gestaoacesso
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gestaoacesso
  template:
    metadata:
      labels:
        app: api-gestaoacesso
    spec:
      containers:
      - name: api-gestaoacesso
        image: lucasmagalhaes88/api-gestaoacesso:1.3
        ports:
        - containerPort: 8000
        env:
          - name: db_host
            valueFrom:
              configMapKeyRef:
                name: api-configmap
                key: db_host

          - name: database
            valueFrom:
              configMapKeyRef:
                name: api-configmap
                key: database

          - name: user
            valueFrom:
              secretKeyRef:
                name: secret-map-api
                key: user

          - name: db_password
            valueFrom:
              secretKeyRef:
                name: secret-map-api
                key: db_password

          
