apiVersion: v1
kind: Service
metadata:
  name: api-service-gestaoacesso
spec:
  type: ClusterIP
  selector:
    app: api-gestaoacesso
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000