apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gestao-acesso-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ui-service-gestaoacesso
            port:
              number: 8080
      - pathType: Prefix
        path: /backend
        backend:
          service:
            name: api-service-gestaoacesso
            port:
              number: 8000