apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-gestaoacesso
  labels:
    app: ui-gestaoacesso
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ui-gestaoacesso
  template:
    metadata:
      labels:
        app: ui-gestaoacesso
    spec:
      containers:
      - name: ui-gestaoacesso
        image: lucasmagalhaes88/ui-gestao-acesso:1.3
        ports:
        - containerPort: 80
