apiVersion: v1
kind: Service
metadata:
  name: ui-service-gestaoacesso
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: ui-gestaoacesso
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80