apiVersion: v1
kind: Service
metadata:
  name: ui-service-gestaoacesso
spec:
  type: NodePort
  selector:
    app: ui-gestaoacesso
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000